import type { Metadata } from "next";
import { Nunito, Permanent_Marker } from "next/font/google";
import "./globals.css";

import Provider from "./provider";

const MyAppFont = Nunito({ subsets: ["latin"] });
const TittleFont = Permanent_Marker({ weight: "400", subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={MyAppFont.className}
      >
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  );
}
